name: Tests
on:
    push:
    pull_request:
    workflow_dispatch:
    workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v7
        - uses: actions/setup-python@v6
          with:
            python-version: '3.14'
        - name: Install requirements
          run: pip install flake8 pycodestyle
        - name: Check syntax
          run: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics --extend-exclude ckan
        - uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b #v4.0.0

  test:
    strategy:
      matrix:
        include: #ckan-image see https://github.com/ckan/ckan-docker-base, ckan-version controls other image tags
          - ckan-version: "2.12"
            ckan-image: "2.12-py3.14"
            experimental: false
          - ckan-version: "master"
            ckan-image: "master"
            experimental: true  # master is unstable, good to know if we are compatible or not
      fail-fast: false

    name: ${{ matrix.experimental && '**Fail_Ignored** ' || '' }} CKAN ${{ matrix.ckan-version }}
    runs-on: ubuntu-latest
    container:
      image: ckan/ckan-dev:${{ matrix.ckan-image }}
      options: --user root
    services:
      solr:
        image: ckan/ckan-solr:${{ matrix.ckan-version }}-solr9
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:7

    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v7
      continue-on-error: ${{ matrix.experimental }}
    - name: Install requirements
      continue-on-error: ${{ matrix.experimental }}
      # Install any extra requirements your extension has here (dev requirements, other extensions etc)
      run: |
        pip install -e .[dev,test]  # Installs the main package and dev dependencies
        playwright install --with-deps
#        pip install -r requirements.txt
#        pip install -r dev-requirements.txt
#        pip install -e .

    - name: Setup extension
      continue-on-error: ${{ matrix.experimental }}
      # Extra initialization steps
      run: |
        # Replace default path to CKAN core config file with the one on the container
        sed -i -e 's/use = config:.*/use = config:\/srv\/app\/src\/ckan\/test-core.ini/' test.ini

        ckan -c test.ini db init
      env:
          CKAN_THEME: bare

    - name: Run tests
      continue-on-error: ${{ matrix.experimental }}
      run: pytest --ckan-ini=test.ini --cov=ckanext.theming --disable-warnings ckanext/theming --junit-xml=/tmp/artifacts/junit/results.xml
      env:
          CKAN_THEME: bare

    - name: Run tests bare theme
      continue-on-error: ${{ matrix.experimental }}
      run: pytest --ckan-ini=test.ini --cov=ckanext.theming --disable-warnings ckanext/theming/themes/bare --junit-xml=/tmp/artifacts/junit/results_theme.xml
      env:
          CKAN_THEME: bare

    - name: ${{ matrix.experimental && '**Fail_Ignored** ' || '' }} Test Summary
      uses: test-summary/action@v2
      continue-on-error: ${{ matrix.experimental }}
      with:
        paths: "/tmp/artifacts/junit/*.xml"
      if: always()

    - name: Install packages required for codecov
      continue-on-error: true
      if: ${{ !cancelled() }}
      run: |
        #ubuntu based images
        apt-get update
        apt-get install -y --no-install-recommends curl gpg

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      if: ${{ !cancelled() }}
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: false # optional (default = false)

    - name: Get Cover
      uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac  # v3.2
      if: ${{ !cancelled() }}
      continue-on-error: true
      with:
        coverageFile: coverage.xml
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload test results to Codecov
      uses: codecov/test-results-action@v1
      if: ${{ !cancelled() }}
      continue-on-error: true
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: false  # optional (default = false)

